"""Abstract broker interface."""
from datetime import date
from decimal import Decimal
from typing import Protocol
from tradebot.core.models import Account, OptionsChain, OrderLeg, OrderResult

class Broker(Protocol):
    async def get_account(self) -> Account: ...
    async def get_positions(self) -> list[dict]: ...
    async def get_options_chain(self, symbol: str, expiration: date) -> OptionsChain: ...
    async def submit_order(self, leg: OrderLeg, price: Decimal) -> OrderResult: ...
    async def submit_multileg_order(self, legs: list[OrderLeg], price: Decimal) -> OrderResult: ...
    async def cancel_order(self, order_id: str) -> None: ...
    async def get_order_status(self, order_id: str) -> str: ...
