"""add json columns to backtest_runs

Revision ID: 958719ad84ee
Revises: e61bf2a69b1d
Create Date: 2026-03-25 22:09:02.604391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '958719ad84ee'
down_revision: Union[str, Sequence[str], None] = 'e61bf2a69b1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('backtest_runs', sa.Column('daily_snapshots', sa.JSON(), nullable=True))
    op.add_column('backtest_runs', sa.Column('trades', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('backtest_runs', 'trades')
    op.drop_column('backtest_runs', 'daily_snapshots')
    # ### end Alembic commands ###
