"""initial schema

Revision ID: c7b0d2ff81b2
Revises: 
Create Date: 2026-03-18 23:21:35.497874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7b0d2ff81b2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('nav', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('realized_pnl', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unrealized_pnl', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('drawdown', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('day_trade_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('snapshot_date')
    )
    op.create_table('day_trade_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('order_id', sa.String(length=50), nullable=False),
    sa.Column('trade_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trades',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('strategy', sa.String(length=100), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('spread_type', sa.String(length=50), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('exit_price', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('pnl', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('entry_time', sa.DateTime(), nullable=False),
    sa.Column('exit_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trade_legs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trade_id', sa.Integer(), nullable=False),
    sa.Column('option_symbol', sa.String(length=50), nullable=False),
    sa.Column('side', sa.String(length=20), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('strike', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('option_type', sa.String(length=10), nullable=False),
    sa.Column('fill_price', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trade_legs')
    op.drop_table('trades')
    op.drop_table('day_trade_log')
    op.drop_table('daily_snapshots')
    # ### end Alembic commands ###
