"""add backtest_runs table

Revision ID: e61bf2a69b1d
Revises: c7b0d2ff81b2
Create Date: 2026-03-19 15:56:04.782197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e61bf2a69b1d'
down_revision: Union[str, Sequence[str], None] = 'c7b0d2ff81b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backtest_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('strategy_name', sa.String(length=100), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('starting_capital', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('interval_minutes', sa.Integer(), nullable=False),
    sa.Column('slippage_pct', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('ending_nav', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_return_pct', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('max_drawdown_pct', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('total_trades', sa.Integer(), nullable=False),
    sa.Column('win_rate', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('profit_factor', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('backtest_runs')
    # ### end Alembic commands ###
